# Generated by Django 5.2.3 on 2025-09-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('longitude', models.FloatField(default=0.0, verbose_name='Longitude')),
                ('latitude', models.FloatField(default=0.0, verbose_name='Latitude')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('landmark', models.CharField(max_length=255, verbose_name='Landmark')),
                ('work_time', models.CharField(max_length=100, verbose_name='Work Time')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Company Profiles',
            },
        ),
        migrations.CreateModel(
            name='CompanySocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('link', models.URLField(verbose_name='Link')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('icon_key', models.CharField(max_length=100, verbose_name='Icon Key')),
            ],
            options={
                'verbose_name': 'Company Social Media',
                'verbose_name_plural': 'Company Social Medias',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('message', models.TextField(verbose_name='Message')),
                ('full_name', models.CharField(max_length=255, verbose_name='Fullname')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('document', models.FileField(upload_to='documents/', verbose_name='Ducument')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
