# Generated by Django 5.2.3 on 2025-09-27 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='BookCategory',
        ),
    ]
